# This is a k3d cluster configuration file for the devplatform cluster which uses flannel which is the default CNI for k3s.

apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: devplatform
servers: 1
agents: 2
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
